export const TransationData = [

  // {
  //   id: 1,
  //   date: "2024-12-24T09:30:00Z",
  //   to: "To Ops / Payroll",
  //   from: "Ops ",
  //   amount: 200,
  //   currency: "AR",
  //   type: "Transfer",
  // },
  // {
  //   id: 1,
  //   date: "2024-12-24T09:30:00Z",
  //   to: "To Ops / Payroll",
  //   from: "Ops ",
  //   amount: 200,
  //   currency: "AR",
  //   type: "Transfer",
  // },
  // {
  //   id: 1,
  //   date: "2024-12-24T09:30:00Z",
  //   to: "To Ops / Payroll",
  //   from: "Ops ",
  //   amount: 200,
  //   currency: "AR",
  //   type: "Transfer",
  // },
  // {
  //   id: 1,
  //   date: "2024-12-24T09:30:00Z",
  //   to: "To Ops / Payroll",
  //   from: "Ops ",
  //   amount: 200,
  //   currency: "AR",
  //   type: "Transfer",
  // },
  // {
  //   id: 1,
  //   date: "2024-12-24T09:30:00Z",
  //   to: "To Ops / Payroll",
  //   from: "Ops ",
  //   amount: 200,
  //   currency: "AR",
  //   type: "Transfer",
  // },
  // {
  //   id: 1,
  //   date: "2024-12-24T09:30:00Z",
  //   to: "To Ops / Payroll",
  //   from: "Ops ",
  //   amount: 200,
  //   currency: "AR",
  //   type: "Transfer",
  // },
  // {
  //   id: 1,
  //   date: "2024-12-26T09:30:00Z",
  //   to: "To Ops / Payroll",
  //   from: "Ops ",
  //   amount: 200,
  //   currency: "AR",
  //   type: "Transfer",
  // },
  // {
  //   id: 1,
  //   date: "2024-12-26T09:30:00Z",
  //   to: "To Ops / Payroll",
  //   from: "Ops ",
  //   amount: 200,
  //   currency: "AR",
  //   type: "Transfer",
  // },
  // {
  //   id: 2,
  //   date: "2023-12-06",
  //   to: "To Ops / Payroll",
  //   amount: -54810.16,
  //   currency: "AR",
  //   type: "Transfer",
  //   attachment: false,
  // },
  // {
  //   id: 3,
  //   date: "2023-12-06",
  //   to: "To Ops / Payroll",
  //   amount: -54810.16,
  //   currency: "AR",
  //   type: "Transfer",
  //   attachment: false,
  // },
  // {
  //   id: 4,
  //   date: "2023-12-06",
  //   to: "To Ops / Payroll",
  //   amount: -54810.16,
  //   currency: "AR",
  //   type: "Transfer",
  //   attachment: true,
  // },
  // {
  //   id: 5,
  //   date: "2023-12-06",
  //   to: "To Ops / Payroll",
  //   amount: 4810.16,
  //   currency: "AR",
  //   type: "Transfer",
  //   attachment: true,
  // },
  // {
  //   id: 6,
  //   date: "2023-12-06",
  //   to: "To Ops / Payroll",
  //   amount: 4810.16,
  //   currency: "AR",
  //   type: "Transfer",
  //   attachment: false,
  // },
  // {
  //   id: 7,
  //   date: "2023-12-06",
  //   to: "To Ops / Payroll",
  //   amount: -54810.16,
  //   currency: "AR",
  //   type: "Transfer",
  //   attachment: false,
  // },
  // {
  //   id: 8,
  //   date: "2023-11-06",
  //   to: "To Ops / Payroll",
  //   amount: -54810.16,
  //   currency: "AR",
  //   type: "Transfer",
  //   attachment: false,
  // },
  // {
  //   id: 9,
  //   date: "2023-11-06",
  //   to: "To Ops / Payroll",
  //   amount: -54810.16,
  //   currency: "AR",
  //   type: "Transfer",
  //   attachment: false,
  // },
  // {
  //   id: 10,
  //   date: "2023-11-06",
  //   to: "To Ops / Payroll",
  //   amount: -54810.16,
  //   currency: "AR",
  //   type: "Transfer",
  //   attachment: true,
  // },
  // {
  //   id: 11,
  //   date: "2023-11-06",
  //   to: "To Ops / Payroll",
  //   amount: -54810.16,
  //   currency: "AR",
  //   type: "Transfer",
  //   attachment: false,
  // },
  // {
  //   id: 12,
  //   date: "2023-11-06",
  //   to: "To Ops / Payroll",
  //   amount: -54810.16,
  //   currency: "AR",
  //   type: "Transfer",
  //   attachment: false,
  // },
  // {
  //   id: 13,
  //   date: "2023-11-06",
  //   to: "To Ops / Payroll",
  //   amount: 200,
  //   currency: "AR",
  //   type: "Transfer",
  //   attachment: false,
  // },
  // {
  //   id: 14,
  //   date: "2023-12-10",
  //   to: "To Ops / Payroll",
  //   amount: -54810.16,
  //   currency: "AR",
  //   type: "Transfer",
  //   attachment: false,
  // },
  // {
  //   id: 15,
  //   date: "2023-12-10",
  //   to: "To Ops / Payroll",
  //   amount: 200,
  //   currency: "AR",
  //   type: "Transfer",
  //   attachment: true,
  // },
  // {
  //   id: 16,
  //   date: "2023-12-11",
  //   to: "To Ops / Payroll",
  //   amount: -54810.16,
  //   currency: "AR",
  //   type: "Transfer",
  //   attachment: false,
  // },
  // {
  //   id: 17,
  //   date: "2023-12-11",
  //   to: "To Ops / Payroll",
  //   amount: -54810.16,
  //   currency: "AR",
  //   type: "Transfer",
  //   attachment: false,
  // },
  // {
  //   id: 18,
  //   date: "2023-12-11",
  //   to: "To Ops / Payroll",
  //   amount: -54810.16,
  //   currency: "AR",
  //   type: "Transfer",
  //   attachment: false,
  // },
  // {
  //   id: 19,
  //   date: "2023-12-11",
  //   to: "To Ops / Payroll",
  //   amount: -54810.16,
  //   currency: "AR",
  //   type: "Transfer",
  //   attachment: false,
  // },
  // {
  //   id: 20,
  //   date: "2023-12-11",
  //   to: "To Ops / Payroll",
  //   amount: -54810.16,
  //   currency: "AR",
  //   type: "Transfer",
  //   attachment: false,
  // },
];
